const furnitureListString = `category	title	price	img	link	description	dimensions
BENCHES	Cosmic Bench	Rs.65,000.00	https://www.mordecor.in/wp-content/uploads/2019/07/1_2_10.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/2_3_10.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/3_2_10.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/4_1_10.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Cosmic-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Outline-Cosmic-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Zoomed-Cosmic-Bench.jpg	https://www.mordecor.in/?product=cosmic-bench	Bring glamorous style to any space at your home. A long foot rest in your master suite or to brighten up any window with style this bench fits the best. The base is founded in Gold Glossy finish which totally compliments the luxury printed fabric. Stitching from the side gives a bloom look to the bench which makes it more wanting for any space at your home.   | ITEM CODE : BE121802 | FINISH : Glossy Gold	DIMENSIONS: 56″x25″, Ht.-17″ | MATERIAL: Stainless Steel and Premium Fabric | STYLE: Modern | WARRANTY: 36 Months
BENCHES	Den Bench	Rs.66,000.00	https://www.mordecor.in/wp-content/uploads/2021/03/1-12.jpg | https://www.mordecor.in/wp-content/uploads/2021/03/2-12.jpg | https://www.mordecor.in/wp-content/uploads/2021/03/3-12.jpg | https://www.mordecor.in/wp-content/uploads/2021/03/4-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/03/5-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/02/Den-benchOutline_image.jpg | https://www.mordecor.in/wp-content/uploads/2021/02/Den-benchOutline.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/02/Den-bench_zoom.jpg	https://www.mordecor.in/?product=den-bench	A great option for breaking up space in an open living area or adding it to your bedroom, benches like this are a versatile touch throughout your home. Crafted from metal base with a foam-filled, leather, and velvet upholstered seat, this piece is perfect for adding an inviting seat wherever it rests. And its tapered, angled legs, streamlined design, and round pillow add a touch of glam to home aesthetics. | ITEM CODE : BE120221 | FINISH :Nickle Matte	DIMENSIONS: 60″x20″, Ht.-17″ | MATERIAL: Stainless Steel and Premium Fabric with leatherette | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Emma Bench	Rs.99,000.00	https://www.mordecor.in/wp-content/uploads/2021/12/1-15.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/2-14.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/3-14.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/4-14.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/5-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_image_Emma-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_Emma-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Emma-Bench_ZOOM.jpg	https://www.mordecor.in/?product=emma-bench	Say hello to the Emma range of finely cushioned bench upholstered in premium velvet and jute like fabric. The gorgeous design and colour, and supreme comfort makes this value for   money bench, a must have for your living room. The legs of the bench are made with metal having gold finish, which brings in the style while the classic black matt finish wooden structure at bottom makes it more comely. It is perfectly proportioned for anywhere in home or office. | ITEM CODE :CO122117 | FINISH :Black Matt	DIMENSIONS: L74″, W-21″, H-27″ | MATERIAL: Stainless Steel and Premium Velvet | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Essence Bench	Rs.82,900.00	https://www.mordecor.in/wp-content/uploads/2019/09/1-29.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/2-28.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/3-27.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/4-22.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/EssenceBench.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/OutlineEssenceBench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/Zoomed-Essence-Bench.jpg	https://www.mordecor.in/?product=essence-bench	Adding a splash of color in your room can never go wrong. Our mint-colored essence bench is the perfect luxury to go for.The perfect amount of metal base gives a classy touch to the bench. Premium fabric hued seating is another great reason to bring this royal piece home. | ITEM CODE : BE061901 | FINISH : Gold Matt	DIMENSIONS: 64″x17″, Ht.-18″ | MATERIAL: Stainless Steel and Premium Fabric | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Loom Bench	Rs.79,800.00	https://www.mordecor.in/wp-content/uploads/2021/05/1-41.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/2-40.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/3-40.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/4-40.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/5-40.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Loom-Bench-_Outline_image.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Loom-Bench-_Outline.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Loom-Bench-_ZOOM.jpg	https://www.mordecor.in/?product=loom-bench	Incredibly designed Loom bench offers an amp fusion of contemporary and conventional vogue. The fine art offers a sophisticated look to adore with ample space and comfort .  Exceptional fusion of elements, transforming traditional to modern concepts offers the perfect blend of metal wood and fabric. Framed in stainless steel in muted black perfectly balances the style, creativity and sturdiness. Upholstered in premium quality fabric with belts the bench spices up any setting. Artistically designed for an amazing look the seating area is clyded with veneer in natural looks. Enjoy the luxury of traditional beauty with a dash of modern design and extreme comfort with unbelievably comfortable Loom bench. | ITEM CODE : BE052128 | FINISH :Matt	DIMENSIONS: 20″ X 60″ , Ht : 32″ | MATERIAL: Premium Fabric , Veneer and Stainless Steel | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Mile Bench	Rs.67,900.00	https://www.mordecor.in/wp-content/uploads/2021/05/1-42.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/2-41.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/3-41.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/4-41.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/5-41.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Mile-bench_Outline_image.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Mile-bench_Outline.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/05/Mile-bench_zoom.jpg	https://www.mordecor.in/?product=mile-bench	Exquisitely crafted Mile bench masters a sleek modern silhouette of its own kind. A distinct concept of creativity, glamour and utility the bench is high on comfort. Taking it cues from the in-vogue   hues and textures of the season the bench offers a fluid and simplistic style to adorne. Upholestered in soft premium jute like fabric the look exudes a cool vibe. Intricately designed the stainless steel legs in glossy gold finish glams up the whole unit to amplify any mood. Whether you are relaxing with your feet up reading or having a sip of coffee you can enjoy the comfort and luxury of this finely cushioned mile bench. Artistically designed for a minimalistic looks the Mile bench promises to suit the practical needs of modern dwellings. | ITEM CODE : BE052129 | FINISH :Gold Glossy	DIMENSIONS: 60″ X 18″ , Ht : 18″ | MATERIAL: Premium Fabric and Stainless Steel | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Olivia Bench	Rs.115,000.00	https://www.mordecor.in/wp-content/uploads/2021/12/1-14.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/2-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/3-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/4-13.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/5-12.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/6-2.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_image_Olivia-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_Olivia-Bench1.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Olivia-Bench-ZOOM.jpg	https://www.mordecor.in/?product=olivia-bench	This dual tone metallic structure is perfectly versatile and is a fusion of old with the new, the bold with muted colors. The premium fabric and well cushioned seat makes it wonderfully quirky,  offering durability and ultimate comfort. The black and gold finish make this bench an element of innate beauty and can be used at the footboard of your bed, under a window or as an additional seating in a small space. | ITEM CODE :BE122113 | FINISH :Black and Gold Matt	DIMENSIONS: L-68″, W-27″, H-28″ | MATERIAL: Stainless Steel and Premium Velvet | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Otto Bench	Rs.99,800.00	https://www.mordecor.in/wp-content/uploads/2021/12/1-16.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/2-15.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/3-15.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/4-15.jpg | https://www.mordecor.in/wp-content/uploads/2021/12/5-14.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_image_Otto-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Outline_Otto-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2021/09/Otto-Bench_ZOOM.jpg	https://www.mordecor.in/?product=otto-bench	Fit for fabulous spaces of elegant extravagance, the Otto Bench is gorgeously glamourous. Individually artisan crafted with a beautiful polished-brass inlay at the bottom and gloss finish  wooden legs, the Otto bench is a striking statement of utter luxury. The superior cushioning ensures extreme comfort.  Ideal for the foot of the bed or as a welcoming feature in the entrance hall, the ottoman is evocative of high-end interior and can be perfectly paired with complementary furnishings. | ITEM CODE :BE052116 | FINISH :Gold Matt	DIMENSIONS: L-60″, W-18″, H-19″ | MATERIAL: Premium Fabric, Wood and Metal detailing | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Roma Bench	Rs.45,000.00	https://www.mordecor.in/wp-content/uploads/2020/09/5-35.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/1-37.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/2-36.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/3-36.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/4-36.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/roma-bench.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/roma-bench_outine-1.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2020/09/roma-bench_zoomed.jpg	https://www.mordecor.in/?product=roma-bench	This bench is a natural fit in at the foot of your bed or beside the front door so you can have a seat while you kick your shoes off. Featuring a foam-filled fabric seat,this bench makes a comfy and upscale addition to your aesthetic, while bronze finished metal legs tie the piece together in subtle style. | ITEM CODE : BE082001 | FINISH : Bronze Fenish	DIMENSIONS: 60″ x 24″, Ht.-16″ | MATERIAL: Stainless Steel base and Premium Velvet | STYLE: Modern | WARRANTY: 365 Days
BENCHES	Statement Bench	Rs.75,000.00	https://www.mordecor.in/wp-content/uploads/2019/07/1_2_10-1.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/2_3_9.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/3_2_9.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/4_1_9.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/statement.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Statement-Bench.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Outline-Outline-statement.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/Zoomed-Statement.jpg	https://www.mordecor.in/?product=statement-bench	Add a contemporary tone with this stylish set at the foot of your bed in your master bedroom or to add the grace of your living room. Crafted using high quality polyurethane foam cushion, a sturdy yet style fitted metal base. The sleek look of this bench makes it more wanting for small spaces. | ITEM CODE : BE121801 | FINISH : Bronze Matt	DIMENSIONS: 61″x18″, Ht.-18 | MATERIAL: Stainless Steel and Premium Fabric | STYLE: Modern | WARRANTY: 36 Months
BENCHES	Valentina Bench	Rs.65,500.00	https://www.mordecor.in/wp-content/uploads/2019/09/1-34.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/2-32.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/3-32.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/4-26.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/5-12.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/valentina-beach.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/valentina-beach-Outline.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg | https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg | https://www.mordecor.in/wp-content/uploads/2019/09/valentina-beach-Zoomed.jpg	https://www.mordecor.in/?product=valentina-bench	Bring this classy affair “Valentina bench” to your master suite or even to your vanity to add glamour. The bench holds a center pleated premium fabric for that chic ambiance. The metallic gold glossy base adds an extra touch to this piece. The perfect stitch with perfect shape is a total yes to add this bench in your abode. | ITEM CODE : BE061902 | FINISH : Chrome	DIMENSIONS: 62″x21″, Ht.-16″ | MATERIAL: Stainless Steel and Premium Fabric | STYLE: Modern | WARRANTY: 365 Days`;

const json = furnitureListString.split("\n");
const keys = json[0].split("\t");

const faltuImages = [
  "https://www.mordecor.in/wp-content/uploads/2019/07/JSL-LOGO.jpg",
  "https://www.mordecor.in/wp-content/uploads/2019/07/download.jpg",
  "https://www.mordecor.in/wp-content/uploads/2019/07/het.jpg",
  "https://www.mordecor.in/wp-content/uploads/2019/12/Zoomed.jpg",
  "https://www.mordecor.in/wp-content/uploads/2019/09/rectra-dining-table.jpg",
  "https://www.mordecor.in/wp-content/uploads/2020/12/outline-5.jpg"
];

const list = json.slice(1).map((row) => {
  const rowJson = row.split("\t");
  return keys.reduce((obj, key, index) => {
    const value = rowJson[index].split(" | ");
    obj[key] = value.length === 1 ? value[0] : value;
    return obj;
  }, {});
});

list.forEach((item) => {
  item.img = item.img.filter((img) => !faltuImages.includes(img));
});

export default list;
